name: Continuous Integration
on:
  push:
    branches:
      - main
  pull_request: {}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # to submit the dependency graph
      security-events: write # to upload SARIF results
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Install inspequte # update PATH before Gradle daemon launches
        uses: KengoTODA/setup-inspequte@main
      - uses: actions/setup-java@de7274f081f381c8f8158605e0321c36c376e2e6 # v6.0.1
        with:
          distribution: temurin
          java-version-file: .java-version
      - name: Build with Gradle
        uses: gradle/actions/setup-gradle@9c971963bec38e04b3d30dcc455b5382be2fdbfb # v6.3.0
        with:
          dependency-graph: generate-and-submit
      - run: ./gradlew build testAggregateTestReport --continue
      - name: Run inspequte
        run: ./gradlew :backend:inspequteMain
      - name: Upload SARIF to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@1c5b675653bb5c22dbe9b12b556ec555138e09fd # v4.38.1
        with:
          sarif_file: backend/build/inspequte/main/report.sarif
      - name: Upload build reports
        if: always()
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6
        with:
          name: build-reports
          path: |
            backend/build/reports
            backend/build/inspequte/*/report.sarif
